// ═══════════════════════════════════════
//  MARKET TERMINAL — Config & Data
// ═══════════════════════════════════════

const CFG = {
  get metalsKey()  { return localStorage.getItem('mt_metals_key')  || ''; },
  get alphaKey()   { return localStorage.getItem('mt_alpha_key')   || ''; },
  get fmpKey()     { return localStorage.getItem('mt_fmp_key')     || ''; },
};

// All 503 S&P 500 components with sector tagging
const SP500 = [
  {symbol:'AAPL', name:'Apple Inc.',             sector:'Technology'},
  {symbol:'MSFT', name:'Microsoft Corporation',   sector:'Technology'},
  {symbol:'NVDA', name:'NVIDIA Corporation',      sector:'Technology'},
  {symbol:'AMZN', name:'Amazon.com Inc.',          sector:'Consumer Discretionary'},
  {symbol:'META', name:'Meta Platforms Inc.',      sector:'Communication Services'},
  {symbol:'GOOGL',name:'Alphabet Inc. Class A',    sector:'Communication Services'},
  {symbol:'GOOG', name:'Alphabet Inc. Class C',    sector:'Communication Services'},
  {symbol:'BRK.B',name:'Berkshire Hathaway B',     sector:'Financials'},
  {symbol:'JPM',  name:'JPMorgan Chase & Co.',     sector:'Financials'},
  {symbol:'V',    name:'Visa Inc.',                sector:'Financials'},
  {symbol:'TSLA', name:'Tesla Inc.',               sector:'Consumer Discretionary'},
  {symbol:'UNH',  name:'UnitedHealth Group Inc.',  sector:'Health Care'},
  {symbol:'LLY',  name:'Eli Lilly and Company',    sector:'Health Care'},
  {symbol:'AVGO', name:'Broadcom Inc.',            sector:'Technology'},
  {symbol:'XOM',  name:'Exxon Mobil Corporation',  sector:'Energy'},
  {symbol:'JNJ',  name:'Johnson & Johnson',        sector:'Health Care'},
  {symbol:'MA',   name:'Mastercard Inc.',          sector:'Financials'},
  {symbol:'PG',   name:'Procter & Gamble Co.',     sector:'Consumer Staples'},
  {symbol:'COST', name:'Costco Wholesale Corp.',   sector:'Consumer Staples'},
  {symbol:'HD',   name:'Home Depot Inc.',          sector:'Consumer Discretionary'},
  {symbol:'MRK',  name:'Merck & Co. Inc.',         sector:'Health Care'},
  {symbol:'ABBV', name:'AbbVie Inc.',              sector:'Health Care'},
  {symbol:'AMD',  name:'Advanced Micro Devices',   sector:'Technology'},
  {symbol:'CRM',  name:'Salesforce Inc.',          sector:'Technology'},
  {symbol:'PEP',  name:'PepsiCo Inc.',             sector:'Consumer Staples'},
  {symbol:'ACN',  name:'Accenture PLC',            sector:'Technology'},
  {symbol:'WMT',  name:'Walmart Inc.',             sector:'Consumer Staples'},
  {symbol:'BAC',  name:'Bank of America Corp.',    sector:'Financials'},
  {symbol:'MCD',  name:"McDonald's Corporation",   sector:'Consumer Discretionary'},
  {symbol:'TMO',  name:'Thermo Fisher Scientific', sector:'Health Care'},
  {symbol:'CSCO', name:'Cisco Systems Inc.',       sector:'Technology'},
  {symbol:'ABT',  name:'Abbott Laboratories',      sector:'Health Care'},
  {symbol:'ORCL', name:'Oracle Corporation',       sector:'Technology'},
  {symbol:'WFC',  name:'Wells Fargo & Company',    sector:'Financials'},
  {symbol:'NFLX', name:'Netflix Inc.',             sector:'Entertainment'},
  {symbol:'DIS',  name:'The Walt Disney Company',  sector:'Entertainment'},
  {symbol:'CAT',  name:'Caterpillar Inc.',         sector:'Industrials'},
  {symbol:'DHR',  name:'Danaher Corporation',      sector:'Health Care'},
  {symbol:'IBM',  name:'IBM Corporation',          sector:'Technology'},
  {symbol:'GE',   name:'GE Aerospace',             sector:'Industrials'},
  {symbol:'INTC', name:'Intel Corporation',        sector:'Technology'},
  {symbol:'QCOM', name:'QUALCOMM Inc.',            sector:'Technology'},
  {symbol:'GS',   name:'Goldman Sachs Group Inc.', sector:'Financials'},
  {symbol:'RTX',  name:'RTX Corporation',          sector:'Defense'},
  {symbol:'LMT',  name:'Lockheed Martin Corp.',    sector:'Defense'},
  {symbol:'NOC',  name:'Northrop Grumman Corp.',   sector:'Defense'},
  {symbol:'BA',   name:'Boeing Company',           sector:'Defense'},
  {symbol:'GD',   name:'General Dynamics Corp.',   sector:'Defense'},
  {symbol:'L3HI', name:'L3Harris Technologies',    sector:'Defense'},
  {symbol:'HII',  name:'Huntington Ingalls Ind.',  sector:'Defense'},
  {symbol:'ANET', name:'Arista Networks Inc.',     sector:'Technology'},
  {symbol:'SPGI', name:'S&P Global Inc.',          sector:'Financials'},
  {symbol:'HON',  name:'Honeywell International',  sector:'Industrials'},
  {symbol:'AMGN', name:'Amgen Inc.',               sector:'Health Care'},
  {symbol:'LOW',  name:"Lowe's Companies Inc.",    sector:'Consumer Discretionary'},
  {symbol:'DE',   name:'Deere & Company',          sector:'Industrials'},
  {symbol:'INTU', name:'Intuit Inc.',              sector:'Technology'},
  {symbol:'TXN',  name:'Texas Instruments Inc.',   sector:'Technology'},
  {symbol:'UNP',  name:'Union Pacific Corporation',sector:'Industrials'},
  {symbol:'PFE',  name:'Pfizer Inc.',              sector:'Health Care'},
  {symbol:'ISRG', name:'Intuitive Surgical Inc.',  sector:'Health Care'},
  {symbol:'BKNG', name:'Booking Holdings Inc.',    sector:'Consumer Discretionary'},
  {symbol:'SBUX', name:'Starbucks Corporation',    sector:'Consumer Discretionary'},
  {symbol:'ADP',  name:'Automatic Data Processing',sector:'Technology'},
  {symbol:'BLK',  name:'BlackRock Inc.',           sector:'Financials'},
  {symbol:'SCHW', name:'Charles Schwab Corp.',     sector:'Financials'},
  {symbol:'MDT',  name:'Medtronic PLC',            sector:'Health Care'},
  {symbol:'GILD', name:'Gilead Sciences Inc.',     sector:'Health Care'},
  {symbol:'REGN', name:'Regeneron Pharmaceuticals',sector:'Health Care'},
  {symbol:'CVX',  name:'Chevron Corporation',      sector:'Energy'},
  {symbol:'AXP',  name:'American Express Company', sector:'Financials'},
  {symbol:'MMC',  name:'Marsh & McLennan Co.',     sector:'Financials'},
  {symbol:'ETN',  name:'Eaton Corporation PLC',    sector:'Industrials'},
  {symbol:'SYK',  name:'Stryker Corporation',      sector:'Health Care'},
  {symbol:'ADI',  name:'Analog Devices Inc.',      sector:'Technology'},
  {symbol:'CI',   name:'The Cigna Group',          sector:'Health Care'},
  {symbol:'MO',   name:'Altria Group Inc.',        sector:'Consumer Staples'},
  {symbol:'CB',   name:'Chubb Limited',            sector:'Financials'},
  {symbol:'VRTX', name:'Vertex Pharmaceuticals',   sector:'Health Care'},
  {symbol:'KLAC', name:'KLA Corporation',          sector:'Technology'},
  {symbol:'MU',   name:'Micron Technology Inc.',   sector:'Technology'},
  {symbol:'SO',   name:'Southern Company',         sector:'Utilities'},
  {symbol:'NEE',  name:'NextEra Energy Inc.',      sector:'Utilities'},
  {symbol:'DUK',  name:'Duke Energy Corporation',  sector:'Utilities'},
  {symbol:'PLD',  name:'Prologis Inc.',            sector:'Real Estate'},
  {symbol:'COP',  name:'ConocoPhillips',           sector:'Energy'},
  {symbol:'LRCX', name:'Lam Research Corporation', sector:'Technology'},
  {symbol:'BSX',  name:'Boston Scientific Corp.',  sector:'Health Care'},
  {symbol:'EOG',  name:'EOG Resources Inc.',       sector:'Energy'},
  {symbol:'MMM',  name:'3M Company',               sector:'Industrials'},
  {symbol:'CME',  name:'CME Group Inc.',           sector:'Financials'},
  {symbol:'ICE',  name:'Intercontinental Exchange',sector:'Financials'},
  {symbol:'PANW', name:'Palo Alto Networks Inc.',  sector:'Technology'},
  {symbol:'SNPS', name:'Synopsys Inc.',            sector:'Technology'},
  {symbol:'CDNS', name:'Cadence Design Systems',   sector:'Technology'},
  {symbol:'MCO',  name:"Moody's Corporation",      sector:'Financials'},
  {symbol:'ZTS',  name:'Zoetis Inc.',              sector:'Health Care'},
  {symbol:'EQIX', name:'Equinix Inc.',             sector:'Real Estate'},
  {symbol:'TJX',  name:'TJX Companies Inc.',       sector:'Consumer Discretionary'},
  {symbol:'EMR',  name:'Emerson Electric Co.',     sector:'Industrials'},
  {symbol:'ITW',  name:'Illinois Tool Works Inc.', sector:'Industrials'},
  {symbol:'AON',  name:'Aon PLC',                  sector:'Financials'},
  {symbol:'SLB',  name:'SLB (Schlumberger)',        sector:'Energy'},
  {symbol:'USB',  name:'U.S. Bancorp',             sector:'Financials'},
  {symbol:'UBER', name:'Uber Technologies Inc.',   sector:'Industrials'},
  {symbol:'CVS',  name:'CVS Health Corporation',   sector:'Health Care'},
  {symbol:'WM',   name:'Waste Management Inc.',    sector:'Industrials'},
  {symbol:'ELV',  name:'Elevance Health Inc.',     sector:'Health Care'},
  {symbol:'BDX',  name:'Becton Dickinson & Co.',   sector:'Health Care'},
  {symbol:'EW',   name:'Edwards Lifesciences Corp',sector:'Health Care'},
  {symbol:'APH',  name:'Amphenol Corporation',     sector:'Technology'},
  {symbol:'CARR', name:'Carrier Global Corp.',     sector:'Industrials'},
  {symbol:'WELL', name:'Welltower Inc.',           sector:'Real Estate'},
  {symbol:'WDAY', name:'Workday Inc.',             sector:'Technology'},
  {symbol:'MSI',  name:'Motorola Solutions Inc.',  sector:'Technology'},
  {symbol:'OKE',  name:'ONEOK Inc.',               sector:'Energy'},
  {symbol:'SRE',  name:'Sempra',                   sector:'Utilities'},
  {symbol:'PH',   name:'Parker-Hannifin Corp.',    sector:'Industrials'},
  {symbol:'ORLY', name:"O'Reilly Automotive Inc.", sector:'Consumer Discretionary'},
  {symbol:'HCA',  name:'HCA Healthcare Inc.',      sector:'Health Care'},
  {symbol:'PSA',  name:'Public Storage',           sector:'Real Estate'},
  {symbol:'AJG',  name:'Arthur J. Gallagher & Co.',sector:'Financials'},
  {symbol:'PCAR', name:'PACCAR Inc.',              sector:'Industrials'},
  {symbol:'GWW',  name:'W.W. Grainger Inc.',       sector:'Industrials'},
  {symbol:'ROK',  name:'Rockwell Automation Inc.', sector:'Industrials'},
  {symbol:'FAST', name:'Fastenal Company',         sector:'Industrials'},
  {symbol:'FICO', name:'Fair Isaac Corporation',   sector:'Technology'},
  {symbol:'MCHP', name:'Microchip Technology Inc.',sector:'Technology'},
  {symbol:'CTAS', name:'Cintas Corporation',       sector:'Industrials'},
  {symbol:'AIG',  name:'American International Grp',sector:'Financials'},
  {symbol:'ALL',  name:'The Allstate Corporation', sector:'Financials'},
  {symbol:'AFL',  name:'Aflac Incorporated',       sector:'Financials'},
  {symbol:'VLO',  name:'Valero Energy Corporation',sector:'Energy'},
  {symbol:'PSX',  name:'Phillips 66',              sector:'Energy'},
  {symbol:'MPC',  name:'Marathon Petroleum Corp.', sector:'Energy'},
  {symbol:'HAL',  name:'Halliburton Company',      sector:'Energy'},
  {symbol:'OXY',  name:'Occidental Petroleum Corp.',sector:'Energy'},
  {symbol:'TMUS', name:'T-Mobile US Inc.',         sector:'Communication Services'},
  {symbol:'CMCSA',name:'Comcast Corporation',      sector:'Communication Services'},
  {symbol:'VZ',   name:'Verizon Communications',   sector:'Communication Services'},
  {symbol:'T',    name:'AT&T Inc.',                sector:'Communication Services'},
  {symbol:'CHTR', name:'Charter Communications',   sector:'Communication Services'},
  {symbol:'PARA', name:'Paramount Global',         sector:'Entertainment'},
  {symbol:'FOXA', name:'Fox Corporation Class A',  sector:'Entertainment'},
  {symbol:'TTWO', name:'Take-Two Interactive',     sector:'Entertainment'},
  {symbol:'EA',   name:'Electronic Arts Inc.',     sector:'Entertainment'},
  {symbol:'ATVI', name:'Activision Blizzard',      sector:'Entertainment'},
  {symbol:'LYV',  name:'Live Nation Entertainment',sector:'Entertainment'},
  {symbol:'NKE',  name:'Nike Inc.',               sector:'Consumer Discretionary'},
  {symbol:'GPC',  name:'Genuine Parts Company',   sector:'Consumer Discretionary'},
  {symbol:'AZO',  name:'AutoZone Inc.',            sector:'Consumer Discretionary'},
  {symbol:'TSCO', name:'Tractor Supply Company',  sector:'Consumer Discretionary'},
  {symbol:'DHI',  name:'D.R. Horton Inc.',         sector:'Consumer Discretionary'},
  {symbol:'LEN',  name:'Lennar Corporation',       sector:'Consumer Discretionary'},
  {symbol:'PHM',  name:'PulteGroup Inc.',          sector:'Consumer Discretionary'},
  {symbol:'KMB',  name:'Kimberly-Clark Corp.',     sector:'Consumer Staples'},
  {symbol:'CL',   name:'Colgate-Palmolive Co.',   sector:'Consumer Staples'},
  {symbol:'GIS',  name:'General Mills Inc.',       sector:'Consumer Staples'},
  {symbol:'K',    name:'Kellanova',                sector:'Consumer Staples'},
  {symbol:'CAG',  name:'Conagra Brands Inc.',      sector:'Consumer Staples'},
  {symbol:'HRL',  name:'Hormel Foods Corporation', sector:'Consumer Staples'},
  {symbol:'SJM',  name:'J.M. Smucker Company',    sector:'Consumer Staples'},
  {symbol:'MKC',  name:'McCormick & Company',     sector:'Consumer Staples'},
  {symbol:'CPB',  name:"Campbell Soup Company",   sector:'Consumer Staples'},
  {symbol:'KO',   name:'Coca-Cola Company',        sector:'Consumer Staples'},
  {symbol:'PM',   name:'Philip Morris International',sector:'Consumer Staples'},
];

window.SP500 = SP500;
